# Generated by Django 3.2.9 on 2022-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
    ]
