# Generated by Django 3.2.9 on 2022-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20220524_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
